# Site settings
title: To the Stars
header-img: img/home-bg.png
email: roiai4@hotmail.com
copyright_name: mdanapalmer
description: > # this means to ignore newlines until "baseurl:"
  coding a smaller universe
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mdanapalmer
learn_profile: mdanapalmer
email_username: roiai4@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
